workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v4
      - node-v6
      - node-v8
      - node-latest

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run flow
      - run: npm test

  node-v4:
    <<: *base
    docker:
      - image: node:4
  node-v6:
    <<: *base
    docker:
      - image: node:6
  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-latest:
    <<: *base
    docker:
      - image: node:latest
